name: DumpDemoForHeliumBalloon
version: 2.0
description: A demo how to create and use dumps in HeliumBalloon
author: Kirastur
website: https://github.com/Kirastur/DumpDemoForHeliumBalloon


api-version: 1.19
load: POSTWORLD
main: de.polarwolf.dumpdemo.Main
depend: [HeliumBalloon]
